# Generated by Django 5.0.6 on 2024-05-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_psat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='collections',
            new_name='collection_users',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='comments',
            new_name='comment_users',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='likes',
            new_name='like_users',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='memos',
            new_name='memo_users',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='opens',
            new_name='open_users',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='rates',
            new_name='rate_users',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='solves',
            new_name='solve_users',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='tags',
            new_name='tag_users',
        ),
    ]
